### ISSUE TITLE
Execute multiple events .

### ISSUE THREAD

**Issue by Sophia-nguyen** [marionettejs/backbone.wreqr#69]
Hi,

In document, we can set multiple handlers  in a single call.
But, can we execute multiple events in a single call ?

Thanks,

**Comment by jmeas** [comment]
Hey there @Sophia-nguyen . Can you elaborate a bit on what you're trying to do? Maybe with some pseudocode? Thanks!

**Comment by Sophia-nguyen** [comment]
Hi Jmeas,

I set some  handlers in a single call:
    Communicator.command.setHandler({
                "command:test1": function() {
                    console.log("command:test1");
                },
                "command:test2": function() {
                    console.log("command:test2");
                },
                "command:test3": function() {
                    console.log("command:test3");
                }
            });

And then, I want execute some events in a single call.
Maybe like this: 
    Communicator.command.execute("command:test1",  "command:test2");

Or anything that I can call many events.

Thanks,

**Comment by jmeas** [comment]
You can't do this with Wreqr, unfortunately, but [Radio](https://github.com/marionettejs/backbone.radio) (which is the successor to this library) has a very similar API as BB.Events.

Using Radio:

```js
Communicator.request('requestOne requestTwo');
```

Does that help?

**Comment by Sophia-nguyen** [comment]
Thank you very much, I will try to work with Radio.

Thanks,

**Comment by jmeas** [comment]
You're welcome!
