### ISSUE TITLE
Incorrect package.json main entry point (path does not exist in repo)

### ISSUE THREAD

**Issue by sberney** [marionettejs/backbone.wreqr#74]
This inaccuracy must be a blast from the past. jspm relies on the the package.json's `main` attribute, which is set to `lib\amd\backbone.wreqr.js`, but there is no folder `lib\amd`. It should presumably read `lib\backbone.wreqr.js`. In addition, the `include` attribute contains a reference to `lib\amd` as well.

Please update package.json!

**Comment by samccone** [comment]
oh dang good catch @sberney , would you be interested in opening up a PR for this?

**Comment by sberney** [comment]
Sure.

**Comment by samccone** [comment]
:clap: :a: :heavy_plus_sign:
