### ISSUE TITLE
Bump and build a new version

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.wreqr#76]
The latest fix needs to get published to npm @samccone

**Comment by samccone** [comment]
:+1: will do

**Comment by SpaceK33z** [comment]
Would it be possible to release it with the latest backbone dep bump? The current release prevents us from upgrading to the latest Backbone :).

**Comment by paulfalgout** [comment]
@SpaceK33z this is happening now https://github.com/marionettejs/backbone.wreqr/pull/78
