### ISSUE TITLE
Support backbone 1.3.3

### ISSUE THREAD

**Issue by chrisronline** [marionettejs/backbone.wreqr#80]
Hey folks,

This package has a [strict dependency range for backbone](https://github.com/marionettejs/backbone.wreqr/blob/master/package.json#L42) but Backbone [recently updated to `1.3.3`](https://github.com/jashkenas/backbone/blob/master/package.json#L35) - is there any reason we can't bump the range to include the newer version?

Thanks

**Comment by jmeas** [comment]
Prob. no reason. We only limit the dependency version because Backbone is unreliable when it comes to breaking changes, so we need to keep it locked down on versions.

Care to make a PR?

**Comment by chrisronline** [comment]
Done ^^
