### ISSUE TITLE
Version range for Backbone invalid in bower.json, installs wrong version

### ISSUE THREAD

**Issue by hashchange** [marionettejs/backbone.wreqr#83]
Same problem as in Backbone.Babysitter, see the [issue there](https://github.com/marionettejs/backbone.babysitter/issues/79).

**Comment by hashchange** [comment]
There you go. If you merge the PR, the fix will be effective with the next patch release, and solve the problem in Marionette 2.x as well.

**Comment by paulfalgout** [comment]
👍

**Comment by codynguyen** [comment]
Is there any update regarding this? It's been a while now and it'd be great if @hashchange's change can be merged in.
